# Generated by Django 5.1.2 on 2024-11-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0005_pokemon_habilidades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='habilidades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
