# Generated by Django 5.1.2 on 2024-11-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0006_alter_pokemon_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenador',
            name='equipo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
