# Generated by Django 5.1.2 on 2024-11-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0010_pokemon_ataque_pokemon_ataque_especial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
