# Generated by Django 5.1.2 on 2024-11-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0012_alter_pokemon_altura_alter_pokemon_ataque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.JSONField(default=list),
        ),
    ]
