# Generated by Django 5.1.2 on 2024-11-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('altura', models.FloatField()),
                ('peso', models.FloatField()),
                ('evolucion', models.CharField(max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='pokemons')),
            ],
        ),
        migrations.CreateModel(
            name='Entrenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pokemons', models.ManyToManyField(to='pokedex.pokemon')),
            ],
        ),
    ]
