# Generated by Django 5.1.2 on 2024-11-17 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_entrenador_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenador',
            name='pokemons',
            field=models.ManyToManyField(blank=True, to='pokedex.pokemon'),
        ),
        migrations.AlterField(
            model_name='entrenador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
