# Generated by Django 5.1.2 on 2024-11-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_alter_pokemon_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='habilidades',
            field=models.JSONField(default=dict),
        ),
    ]
