# Generated by Django 5.1.2 on 2024-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0013_alter_pokemon_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='tipo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
